function jac = num_jacobian(q1,q2,q3,q4,q5,x,y)
%NUM_JACOBIAN
%    JAC = NUM_JACOBIAN(Q1,Q2,Q3,Q4,Q5,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Dec-2023 12:43:01

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t16 = -t13;
t17 = -t14;
t18 = -t15;
t19 = t13+t14;
t20 = t12+t18;
t21 = t4.*t19;
t22 = t9.*t19;
t23 = t4.*t20;
t24 = -t21;
t25 = t9.*t20;
t26 = -t22;
t27 = -t25;
t28 = t21+t25;
t29 = t23+t26;
t32 = -t5.*(t22-t23);
t34 = -t10.*(t22-t23);
t36 = t10.*(t22-t23);
t30 = t5.*t28;
t31 = t10.*t28;
t33 = -t30;
t35 = -t31;
t37 = t30+t34;
t43 = -t6.*(t31+t5.*(t22-t23));
t45 = t11.*(t31+t5.*(t22-t23));
t38 = t32+t35;
t39 = t11.*t37;
t40 = t6.*t37;
t42 = -t39;
t44 = -t40;
t46 = t20+t29+t38+t42+t43;
t47 = t16+t17+t24+t27+t33+t36+t44+t45;
jac = reshape([t47,t46,t47,t46,t24+t27+t33+t36+t44+t45,t29+t38+t42+t43,t33+t36+t44+t45,t38+t42+t43,t44+t45,t42+t43,-1.0,0.0,0.0,-1.0],[2,7]);
end
